# Generated by Django 2.1.5 on 2019-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiencesBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('story', models.ManyToManyField(to='HumanH.HumanStory', verbose_name='Experience Title')),
            ],
        ),
    ]
