# Generated by Django 2.1.5 on 2019-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanH', '0003_auto_20190325_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tutorial_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='experiencesby',
            name='story',
        ),
        migrations.RemoveField(
            model_name='humanstory',
            name='story_teller',
        ),
        migrations.DeleteModel(
            name='ExperiencesBy',
        ),
        migrations.DeleteModel(
            name='HumanStory',
        ),
    ]
